name: Build Images

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.generate.outputs.tag }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: generate
      run: echo "tag=$(./hack/image-tag)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to Alicloud Docker registry
      uses: docker/login-action@v2
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.ALI_REGISTRY_USER }}
        password: ${{ secrets.ALI_REGISTRY_PASS }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push Docker images
      run: |
        GOPROXY=https://proxy.golang.org,direct TAG=${{needs.generate.outputs.image-tag}} make push-image
      env:
        TARGET: ${{ github.event.inputs.target }}